name: build-gh-action
on:
  workflow_dispatch:

  # push:
  #   branches:
  #     - main
jobs:
  build-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Setup Timoni
        uses: stefanprodan/timoni/actions/setup@main
      - name: Setup Task
        uses: arduino/setup-task@v1
      - name: Install Chainsaw
        uses: kyverno/action-install-chainsaw@v0.1.7
      - name: Setup up
        run: |
          curl -sL https://cli.upbound.io | sh
          mv up /usr/local/bin/
      - name: Test
        run: task test
      - name: Publish
        run: task package-publish
        env:
          UP_ACCOUNT: ${{ secrets.UP_ACCOUNT }}
          UP_TOKEN: ${{ secrets.UP_TOKEN }}
          VERSION: v0.12.${{ github.run_number }}
      - name: Commit changes
        run: |
          git config --local user.email "daryl@datametal.io"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "Config update [skip ci]"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.CROSSPLANE_TOKEN }}
          branch: ${{ github.ref }}
